### ISSUE TITLE
Users of the remind system

### ISSUE THREAD

**Issue by hemirt** [hemirt/WNMAbot#31]
Are there any serious users of the remind system? Due to new data handling system I'm planning on completely removing it, but if there are users of it I might rewrite it instead.

// edit: not to be confused with !notify / !comebackmsg system
// edit2: also if you have any suggestion what to rewrite better, post them here too

**Comment by TranRed** [comment]
I'm using it :) / 

mostly as time for food related stuff Kapp

**Comment by hemirt** [comment]
thanks for your continued patronage @TranRed
