### ISSUE TITLE
Kind of a repeat/similar issue but regarding notify blacklist

### ISSUE THREAD

**Issue by PotehtoO** [hemirt/WNMAbot#39]
Hi,

Am a moderator for Nymn chat, as would come with moderating there would be users that dislike moderators if and for moderating chat, would just like to request for blacklist from the !notify command from futuregadget8(or any form of mentioning in fact) as there is a user trying to use the bot to harass me by proxy. Twitch username is same as github username, would greatly appreciate it.

Also, while understandable I could userignore with chatterino, people with brain damage still get satisfaction from thinking that I get and see their message so that kinda bothers me, though I know it's not exactly relevant to you whether or not it's bothering me.

Thanks and Regards.

**Comment by hemirt** [comment]
solved
